### ISSUE TITLE
Changing the "Folders" property

### ISSUE THREAD

**Issue by astreloff** [gr0grig/obsidian-virt-folder#1]
Add the ability to customize "Folders" property name instead of using a hardcoded value. This allows smooth transition or easier integration with other plugins.

E.g. I already have some kind of hierarchy using property with name "parent".

**Comment by gr0grig** [comment]
ok, in the next release

**Comment by gr0grig** [comment]
@astreloff Test it, it should work

https://github.com/gr0grig/obsidian-virt-folder/releases/tag/1.0.3

**Comment by astreloff** [comment]
It works, ty!
