### ISSUE TITLE
Label from properties

### ISSUE THREAD

**Issue by johnfuller** [gr0grig/obsidian-virt-folder#2]
Zettel types of systems may need to exist in a vault with existing file naming conventions which can't be changed. Allow labels in the tree view to be pulled from a property rather than the file name.

**Comment by gr0grig** [comment]
OK. I'll do it in my free time.

**Comment by gr0grig** [comment]
Please [test it](https://github.com/gr0grig/obsidian-virt-folder/releases/tag/1.0.4) and tell me if you have some problems with any of the commands.

**Comment by johnfuller** [comment]
It's working so far. I'll be testing this more through the day, and I'll let you know if I run into any issues. One item I did find is that it doesn't work with aliases. My guess is that this is because aliases are like an array field type rather than text. This is fine for my use-case, but this should be mentioned in the documentation and settings as a restriction in property types.

**Comment by johnfuller** [comment]
When I use a property for the label of the file, I can only find the file via "add folder" via the entry in that property. In other words, I can't search the list via file names. If I add the file name manually to the folder property, then it doesn't recognize that file (unlinked text color.) I can instead search the list for the label name, and the file then gets added to the folder property with the file name and the link color. I don't think this is a critical issue, but feels like odd behavior.

**Comment by gr0grig** [comment]
I found another problem, sorting is by file name, not title. 

Regarding aliases, I don’t fully understand how to display them, should the first name in the list be the title?

**Comment by johnfuller** [comment]
The alias property type is a list. 

https://help.obsidian.md/Linking+notes+and+files/Aliases

https://help.obsidian.md/Editing+and+formatting/Properties#Property+types

You might take a look at this plugin and do a search in the codebase for alias to see how it handles this.

https://github.com/snezhig/obsidian-front-matter-title/

My guess is that taking the first available alias would be best.

**Comment by johnfuller** [comment]
Another UI concern is that when I try to add a folder, the modal search shows the "label name" rather than the file name. For example, if the filename is "foo" but I used your added feature to reference the file as "bar" then the file would show as "bar" in the modal search. Maybe this is actually the best way, but it's something to consider. I feel the search in the modal should show file names, but that's just a preference. The way it is now is fine. I just add the file manually to the "folders" property anyway.

**Comment by gr0grig** [comment]
There are systems where the file name is a unique number, and the title is specified in the metadata. I don't quite understand which system you're using. Why use both the file name on the disk and the title at the same time?

**Comment by johnfuller** [comment]
I think it's fine without aliases. I was thinking about this from a support perspective, and just something to be aware of. I think a lot of users would use alias first as the label. If alias doesn't work, then it might cause confusion. I don't use aliases myself. I'm fine with the add-on as it is. You might add in the documentation and settings that you must use a text property type.

**Comment by gr0grig** [comment]
I will add aliases, but I'm trying to understand how your archive is structured to better solve the problem.

**Comment by johnfuller** [comment]
> Why use both the file name on the disk and the title at the same time?

Sorry about that. I really like the UI which your add-on enables. I haven't been using Zettelkasten, but I may start.

My thinking is that an object (file?) in a system can have many different names based on context. In the context of a file system, I name my files based on a timestamp as a UID. For example, right this moment is 20240728115630 in the Philippines. But that file name is useless in any other context. In a table of contents, I might want for the file to be shown as "Foo." In a Zettelkasten list, I might want for the file to be shown as 9/8. I almost never use the actual file names as labels. And I use that UID type scheme because much of my activity is logging types of activity which just needs a UID.

The above brings up an interesting question. If you're going to actually search for the object, then what should be the default search criteria? I feel it should be the file name. So, when you run the "Add Folder" command, you should see file names. With this feature change, you see the labels (and file name as a backup if there is no label.) I'm actually fine with it as is. I just thought I would mention it though.

**Comment by gr0grig** [comment]
I think I got it. I need to add a setting to use for searching - file name or title. Right?

**Comment by johnfuller** [comment]
I think it's best to go by convention. If you have to select from a list of items (such as by modal) then what's the expected behavior? I would expect that I would need to know the file name. I think adding an option to search by either would be more work than it's worth and it clutters the UI. I think it would be more worth it to focus on other features. So, I would either leave it as it as or change it so that file names appear in the modal rather than labels.

**Comment by gr0grig** [comment]
Added a couple of new settings, including how to display the title in commands

https://github.com/gr0grig/obsidian-virt-folder/releases/tag/1.0.5

**Comment by johnfuller** [comment]
It works great, thanks! I think we can close this now.
