### ISSUE TITLE
[Feature Request] Option to Drag and Drop to Nest/Rearrange Virtual Folders

### ISSUE THREAD

**Issue by obsidiest** [gr0grig/obsidian-virt-folder#6]
I understand at the moment it's possible to edit the values of the `Folders` property of individual files to nest/rearrange virtual folders, but I think being able to do it from the virtual folder pane would be useful as well, such as when organizing larger vaults.

**Comment by gr0grig** [comment]
This has already been asked, I will do it when I have time.
